Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2018-10, with the labels that each got.

#112 Update OWNERS to match cluster-api OWNERS state
  OWNERS
  OWNERS_ALIASES
Labels: do-not-merge/hold

#114 Update Project Status README section
  README.md
Labels: approved, lgtm, release-note-none, size/XS

#116 Remove recommended Minikube version
  README.md
Labels: approved, lgtm, size/XS

#108 Add SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: approved, lgtm, lifecycle/active, size/S

#117 Update Go import paths and links to sigs.k8s.io/cluster-api-provider-digitalocean
  .circleci/config.yml
  CONTRIBUTING.md
  Makefile
  README.md
  cloud/digitalocean/actuators/machine/actuator.go
  cloud/digitalocean/actuators/machine/userdata.go
  cloud/digitalocean/controllers/cluster/controller.go
  cloud/digitalocean/controllers/machine/controller.go
  cloud/digitalocean/providerconfig/doc.go
  cloud/digitalocean/providerconfig/v1alpha1/doc.go
  cloud/digitalocean/providerconfig/v1alpha1/register.go
  clusterctl/main.go
  cmd/cluster-controller/Dockerfile
  cmd/cluster-controller/main.go
  cmd/machine-controller/Dockerfile
  cmd/machine-controller/main.go
  pkg/docker/docker.go
  pkg/docker/ubuntu/ubuntu.go
  pkg/scp/scp.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#118 Makefile: add verify rule
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS
