Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2020-05, with the labels that each got.

#151 🏃dependencies: update several dependencies
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#152 Update golangci-lint to v1.26.0
  .golangci.yml
  api/v1alpha2/docluster_types.go
  api/v1alpha2/domachine_types.go
  api/v1alpha2/domachinetemplate_types.go
  api/v1alpha2/tags.go
  api/v1alpha2/types.go
  cloud/scope/cluster.go
  cloud/scope/machine.go
  cloud/services/computes/droplets.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_doclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_domachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_domachinetemplates.yaml
  controllers/docluster_controller.go
  controllers/domachine_controller.go
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#155 add cloudbuild
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#154 makefile: update registry location and update release steps
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#153 Add initial Tilt definition
  .gitignore
  Makefile
  scripts/kind-with-registry.sh
  tilt-provider.json
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#156 Prepare e2e-test on prowjob
  hack/ensure-doctl.sh
  scripts/ci-e2e.sh
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#158 Use random ssh-key name for e2e test
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#159 images: fix images name
  Makefile
  config/default/manager_image_patch.yaml
  skaffold.yaml
  tilt-provider.json
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#160 images: fix images name
  Makefile
  config/default/manager_image_patch.yaml
  skaffold.yaml
  tilt-provider.json
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#161 Use gcr.io/distroless/static:latest in Dockerfile
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#162 [release-0.3] Use gcr.io/distroless/static:latest in Dockerfile
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#163 Drop buildkit from Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#164 Drop buildkit from Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#165 Add MachineDeployment e2e test
  test/e2e/e2e_test.go
  test/e2e/resource_generator.go
  test/e2e/utils.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#166 makefile: revert the buildKit but set to disable by default
  Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#167 Updated docs
  README.md
  docs/roadmap.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M
