Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2020-03, with the labels that each got.

#141 Remove nikhita as cluster-api-do-maintainer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#142 Remove alvaroaleman from owners
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#144 Update OWNERS file to match CAPI OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#143 Remove andrewsykim from owners
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#145 Add cpanato and prksu as maintainers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#147 Fix README typo and link to cloud-init doc
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#146 Add MorrisLaw as a maintainer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#148 Initial e2e-test
  Makefile
  go.mod
  go.sum
  test/e2e/README.md
  test/e2e/e2e_test.go
  test/e2e/manifests/digitalocean-cloud-controller-manager.yaml
  test/e2e/resource_generator.go
  test/e2e/suite_test.go
  test/e2e/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL
