Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2020-10, with the labels that each got.

#192 makefile: remove unused test-integration
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#200 dependencies: update several dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/L

#193 📖 Add releasing doc
  Makefile
  docs/releasing.md
Labels: approved, cncf-cla: yes, hacktoberfest, lgtm, release-note-none, size/M
