Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2020-09, with the labels that each got.

#188 fix metadata.yaml to use the correct release
  metadata.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#189 revert https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/188
  metadata.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#190 Update e2e test to use capi e2e framework
  .gitignore
  Makefile
  go.mod
  go.sum
  hack/ensure-go.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  scripts/ci-e2e.sh
  test/e2e/README.md
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
  test/e2e/data/ccm/digitalocean-cloud-controller-manager.yaml
  test/e2e/data/cni/calico/calico.yaml
  test/e2e/data/infrastructure-digitalocean/cluster-template.yaml
  test/e2e/data/infrastructure-digitalocean/metadata.yaml
  test/e2e/e2e_test.go
  test/e2e/resource_generator.go
  test/e2e/suite_test.go
  test/e2e/utils.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XXL

#191 Add md scaling and HA cluster creation e2e test
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L
