Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2020-06, with the labels that each got.

#171 Try to increase timeout when ensuring machine node ref
  test/e2e/utils.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#169 dependencies: update several dependencies
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#172 Change repository uri to match format for kustomize >= 3.5.5
  examples/addons.yaml
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS
