Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2020-12, with the labels that each got.

#207 Fix manager tolerations patch for provider-components
  examples/provider-components/manager_tolerations_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#210 Improve getting started guide
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#209 Add missing clusterName to Machine
  examples/controlplane/controlplane.yaml
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#212 dependencies: update several dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#216 Avoid panic on network error in DO API get requests
  cloud/services/computes/droplets.go
  cloud/services/networking/loadbalancers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#215 Do not mark droplet create failures as terminal
  controllers/domachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#220 Remove finalizer when cloud resource is found absent
  controllers/docluster_controller.go
  controllers/domachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#221 Fix typo
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#223 [0.4] ncdc stepping down from maintainership
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#222 ncdc stepping down from maintainership
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#227 Update CAPI to v0.3.12
  go.mod
  go.sum
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#226 Let CCM reach API server through k8s svc to avoid bad TLS cert
  examples/digitalocean-cloud-controller-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#229 Updated some log messages throughout the code so that they read more easily.
  hack/do-janitor/do-janitor.go
  test/e2e/clean_resources.go
  test/e2e/common.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#224 Update doc for v0.4
  README.md
  docs/getting-started.md
  examples/addons.yaml
  examples/cluster/cluster.yaml
  examples/cluster/kustomization.yaml
  examples/cluster/kustomizeconfig.yaml
  examples/controlplane/controlplane.yaml
  examples/controlplane/kustomization.yaml
  examples/controlplane/kustomizeconfig.yaml
  examples/core-components/kustomization.yaml
  examples/core-components/manager_tolerations_patch.yaml
  examples/digitalocean-cloud-controller-manager.yaml
  examples/digitalocean-csi.yaml
  examples/generate.sh
  examples/machinedeployment/kustomization.yaml
  examples/machinedeployment/kustomizeconfig.yaml
  examples/machinedeployment/machinedeployment.yaml
  examples/provider-components/kustomization.yaml
  examples/provider-components/manager_tolerations_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL
