Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2021-02, with the labels that each got.

#233 Add Cluster UID in Loadbalancer name and Droplet target tag
  api/v1alpha3/tags.go
  api/v1alpha3/tags_test.go
  cloud/scope/cluster.go
  cloud/services/computes/droplets.go
  cloud/services/networking/loadbalancers.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#234 Update OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#232 Add managed DNS record support for API endpoint
  api/v1alpha3/docluster_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  cloud/scope/clients.go
  cloud/scope/cluster.go
  cloud/services/networking/dns.go
  cloud/services/networking/domains.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_doclusters.yaml
  controllers/docluster_controller.go
  controllers/docluster_controller_test.go
  go.mod
  go.sum
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XL

#236 Update SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
