Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2021-01, with the labels that each got.

#228 Add external storage support for etcd
  api/v1alpha3/domachine_types.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  cloud/scope/clients.go
  cloud/scope/cluster.go
  cloud/services/computes/droplets.go
  cloud/services/computes/volumes.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_domachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_domachinetemplates.yaml
  controllers/domachine_controller.go
  templates/cluster-template-ext-etcd-storage.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#225 Support specifying VPC
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  cloud/services/computes/droplets.go
  cloud/services/networking/loadbalancers.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_doclusters.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#230 Remove deprecate generate-examples Makefile target
  Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
