Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2021-06, with the labels that each got.

#259 Update CAPI to v0.4.0-beta.0
  Dockerfile
  Makefile
  go.mod
  go.sum
  templates/cluster-template-ext-etcd-storage.yaml
  templates/cluster-template.yaml
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
  test/e2e/data/infrastructure-digitalocean/cluster-template.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#260 capi: using released artifacts
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#262 Add IPFamily to fix CAPI test
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#265 Update CAPI release to v0.4.0-beta.1
  go.mod
  go.sum
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#264 Update janitor job to remove volumes used by kops e2e jobs
  hack/do-janitor/do-janitor.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#266 Update CAPI to v0.4.0
  go.mod
  go.sum
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L
