Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2021-12, with the labels that each got.

#286 CAPI: update to release v1.0.2 and project dependencies
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
Labels: approved, lgtm, size/M, release-note, cncf-cla: yes

#287 Fix controlPlaneEndpoint validation error message
  api/v1beta1/docluster_webhook.go
Labels: approved, lgtm, size/XS, release-note, cncf-cla: yes

#288 Update the compatibility matrix
  README.md
Labels: approved, size/S, lgtm, release-note-none, cncf-cla: yes

#289 Fix controlPlaneEndpoint validation error message (release-1.0)
  api/v1beta1/docluster_webhook.go
Labels: approved, lgtm, size/XS, release-note, cncf-cla: yes
