Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2021-03, with the labels that each got.

#240 enable metrics scraping via prometheus
  config/rbac/auth_proxy_service.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#242 Omitempty ControlPlaneDNS
  api/v1alpha3/docluster_types.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#241 Add admission webhook
  api/v1alpha3/docluster_webhook.go
  api/v1alpha3/domachine_webhook.go
  api/v1alpha3/domachinetemplate_webhook.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_doclusters.yaml
  config/crd/patches/cainjection_in_domachines.yaml
  config/crd/patches/cainjection_in_domachinetemplates.yaml
  config/crd/patches/webhook_in_doclusters.yaml
  config/crd/patches/webhook_in_domachines.yaml
  config/crd/patches/webhook_in_domachinetemplates.yaml
  config/kustomization.yaml
  config/patch_crd_webhook_namespace.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manager_webhook_patch.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  main.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XL

#244 [Clean Up] Refactor e2e test and update several dependencies
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/ensure-go.sh
  skaffold.yaml
  test/e2e/capdo_test.go
  test/e2e/capi_test.go
  test/e2e/common.go
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
  test/e2e/conformance_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#246 Minimize API requests by skipping to check a given image ID
  cloud/services/computes/droplets.go
  cloud/services/computes/images.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#245 Move dns propagnation helpers to own packages
  api/v1alpha3/docluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_doclusters.yaml
  controllers/docluster_controller.go
  main.go
  util/dns/dns.go
  util/dns/dns_test.go
  util/dns/resolver/faker.go
  util/dns/resolver/resolver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#243 Update klog dependency to v2
  cloud/scope/cluster.go
  cloud/scope/machine.go
  controllers/domachine_controller_unit_test.go
  controllers/suite_test.go
  go.mod
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#250 Make conversion-gen output location explicit
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#252 Support capi paused annotation
  controllers/docluster_controller.go
  controllers/domachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#253 [backport] Support capi paused annotation
  controllers/docluster_controller.go
  controllers/domachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M
