Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2022-02, with the labels that each got.

#292 Update the compatibility matrix checkbox for v1.0
  README.md
Labels: approved, lgtm, size/XS, release-note-none, cncf-cla: yes

#293 update to use the current minikube drivers link
  docs/getting-started.md
Labels: approved, lgtm, size/XS, release-note-none, cncf-cla: yes

#294 update capi to v1.1.0
  Makefile
  Tiltfile
  clusterctl-settings.json
  go.mod
  go.sum
  metadata.yaml
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
  test/e2e/data/metadata/cluster-api-provider-digitalocean/metadata.yaml
  test/e2e/data/metadata/cluster-api/metadata.yaml
Labels: approved, lgtm, size/L, release-note, cncf-cla: yes

#296 [release-1.0] update capi to 1.0.4
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
Labels: approved, lgtm, size/M, release-note, cncf-cla: yes

#297 [release-0.5] Update go and capi
  Dockerfile
  Makefile
  go.mod
  go.sum
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
Labels: approved, lgtm, size/M, release-note, cncf-cla: yes

#298 go update to 1.16.13 and some dependencies updates
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: approved, lgtm, size/M, release-note, cncf-cla: yes

#299 Update image / go and capi also calico and ccm
  Dockerfile
  Makefile
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
  test/e2e/data/ccm/digitalocean-cloud-controller-manager.yaml
  test/e2e/data/cni/calico/calico.yaml
Labels: approved, lgtm, size/XXL, release-note, cncf-cla: yes

#300 add pause annotation check
  Dockerfile
  Makefile
  controllers/docluster_controller.go
  controllers/domachine_controller.go
  scripts/kind-with-registry.sh
Labels: kind/feature, approved, lgtm, size/L, release-note, cncf-cla: yes

#301 tests/e2e: add remediation tests
  test/e2e/capi_test.go
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/data/infrastructure-digitalocean/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-digitalocean/cluster-template-md-remediation.yaml
Labels: kind/feature, approved, lgtm, size/L, release-note, cncf-cla: yes

#302 e2e/tests: add upgrade k8s tests
  Makefile
  go.mod
  go.sum
  test/e2e/capi_test.go
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/data/infrastructure-digitalocean/cluster-template-upgrades.yaml
Labels: kind/feature, approved, lgtm, size/L, release-note, cncf-cla: yes

#304 align manager flag names with upstream Kubernetes components and add other flags
  config/manager/manager.yaml
  controllers/docluster_controller.go
  controllers/domachine_controller.go
  go.mod
  go.sum
  main.go
  util/reconciler/defaults.go
  util/reconciler/defaults_test.go
Labels: kind/feature, kind/cleanup, approved, lgtm, size/L, release-note, cncf-cla: yes

#306 owners: add missing emeritus members and sync capi owners
  OWNERS
  OWNERS_ALIASES
Labels: approved, size/S, lgtm, release-note-none, cncf-cla: yes

#305 add dependabot config
  .github/dependabot.yml
Labels: kind/cleanup, approved, size/S, lgtm, release-note, cncf-cla: yes

#291 add lb uuid to docluster spec
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_doclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_doclustertemplates.yaml
  controllers/docluster_controller.go
Labels: approved, lgtm, size/M, release-note, ok-to-test, cncf-cla: yes

#315 Add E2E Conformance tests using k8s ci artifacts
  go.mod
  go.sum
  scripts/ci-conformance.sh
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
  test/e2e/conformance_test.go
  test/e2e/data/ccm/digitalocean-cloud-controller-manager.yaml
  test/e2e/data/cni/calico/calico.yaml
  test/e2e/data/infrastructure-digitalocean/cluster-template-prow-ci-version.yaml
  test/e2e/suite_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note, cncf-cla: yes
