Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2022-06, with the labels that each got.

#351 Update CAPI to v1.1.4 and go to 1.17.11
  Dockerfile
  Makefile
  Tiltfile
  config/certmanager/certificate.yaml
  config/default/kustomization.yaml
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
Labels: approved, lgtm, size/XL, release-note, ok-to-test, cncf-cla: yes

#353 bump golangci-lint version to v1.46.2
  Makefile
Labels: approved, lgtm, size/XS, release-note, cncf-cla: yes

#358 cherry picks and dependencies updates to release-1.1 branch
  Dockerfile
  Makefile
  Tiltfile
  config/certmanager/certificate.yaml
  config/default/kustomization.yaml
  go.mod
  go.sum
  hack/install-cert-manager.sh
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
Labels: approved, lgtm, size/XL, release-note, cncf-cla: yes
