Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2022-10, with the labels that each got.

#403 Switch to non-preformatted etcd DOBS volumes
  templates/cluster-template-ext-etcd-storage.yaml
Labels: approved, lgtm, size/XS, release-note-none, needs-ok-to-test, cncf-cla: yes

#404 Add volumes field to DOMachine status
  api/v1alpha3/domachine_types.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/domachine_types.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/domachine_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/machine.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_domachines.yaml
  controllers/domachine_controller.go
Labels: approved, lgtm, size/L, release-note, ok-to-test, cncf-cla: yes, hacktoberfest

#406 bump capi to v1.2.3
  Dockerfile
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
Labels: kind/feature, approved, lgtm, size/M, release-note, cncf-cla: yes

#380 clean up ssh keys when cleaning up e2e test resources
  hack/do-janitor/do-janitor.go
Labels: approved, lgtm, size/M, release-note-none, cncf-cla: yes

#412 bump CAPI to v1.2.4
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
Labels: kind/feature, approved, lgtm, size/M, release-note, cncf-cla: yes

#413 docs: Correction of generating a workload cluster command
  docs/getting-started.md
Labels: approved, lgtm, size/XS, release-note-none, ok-to-test, cncf-cla: yes
