Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2023-10, with the labels that each got.

#525 Allow customization of client-go throttling
  main.go
Labels: approved, size/S, lgtm, release-note, cncf-cla: yes

#509 Update dependencies and CAPI to 1.4
  .golangci.yml
  Dockerfile
  Makefile
  Tiltfile
  cloud/scope/machine.go
  cloud/services/computes/droplets_test.go
  controllers/docluster_controller.go
  controllers/domachine_controller.go
  controllers/domachine_controller_unit_test.go
  go.mod
  go.sum
  hack/ensure-go.sh
  metadata.yaml
  test/e2e/capi_test.go
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
  test/e2e/data/metadata/cluster-api/metadata.yaml
Labels: approved, lgtm, size/L, release-note, ok-to-test, cncf-cla: yes, tide/merge-method-squash

#533 Updates for lint job and Go for the image
  .github/workflows/lint.yml
  Dockerfile
  controllers/docluster_controller.go
  controllers/domachine_controller.go
Labels: kind/feature, approved, size/S, lgtm, release-note, cncf-cla: yes

#535 update do ccm to 0.1.45
  test/e2e/data/ccm/digitalocean-cloud-controller-manager.yaml
Labels: approved, lgtm, size/XS, release-note, cncf-cla: yes

#541 [release-1.4] update CAPI to 1.4.8
  Makefile
  Tiltfile
  go.mod
  go.sum
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
Labels: kind/feature, kind/cleanup, approved, lgtm, size/M, release-note, cncf-cla: yes

#527 Update dependencies and CAPI to 1.5
  Makefile
  Tiltfile
  api/v1beta1/docluster_webhook.go
  api/v1beta1/doclustertemplate_webhook.go
  api/v1beta1/domachine_webhook.go
  api/v1beta1/domachinetemplate_webhook.go
  controllers/docluster_controller.go
  controllers/domachine_controller.go
  controllers/domachine_controller_unit_test.go
  go.mod
  go.sum
  metadata.yaml
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
  test/e2e/data/metadata/cluster-api/metadata.yaml
Labels: approved, lgtm, size/L, release-note, ok-to-test, cncf-cla: yes
