Repository kubernetes-sigs/cluster-api-provider-digitalocean, pull requests merged in 2023-01, with the labels that each got.

#438 Upgrade ginkgo
  .github/dependabot.yml
  .golangci.yml
  Dockerfile
  Makefile
  Tiltfile
  cloud/services/computes/sshkeys.go
  clusterctl-settings.json
  controllers/suite_test.go
  go.mod
  go.sum
  hack/do-janitor/do-janitor.go
  hack/ensure-go.sh
  hack/install-cert-manager.sh
  main.go
  metadata.yaml
  scripts/go_install.sh
  test/e2e/capdo_test.go
  test/e2e/capi_test.go
  test/e2e/common.go
  test/e2e/config/digitalocean-ci.yaml
  test/e2e/config/digitalocean-dev.yaml
  test/e2e/conformance_test.go
  test/e2e/data/cni/calico/calico.yaml
  test/e2e/data/infrastructure-digitalocean/cluster-template-upgrades.yaml
  test/e2e/data/metadata/cluster-api-provider-digitalocean/metadata.yaml
  test/e2e/data/metadata/cluster-api/metadata.yaml
  test/e2e/suite_test.go
Labels: kind/feature, kind/cleanup, approved, lgtm, size/XXL, release-note, cncf-cla: yes

#443 update ccm to 0.1.42 release
  test/e2e/data/ccm/digitalocean-cloud-controller-manager.yaml
Labels: kind/feature, approved, lgtm, size/XS, release-note, cncf-cla: yes

#450 Cloud unit test
  Makefile
  cloud/services/computes/droplets_test.go
  cloud/services/computes/mock_computes/doc.go
  cloud/services/computes/mock_computes/droplets_mock.go
  cloud/services/computes/mock_computes/images_mock.go
  cloud/services/computes/mock_computes/sshkeys_mock.go
  cloud/services/computes/mock_computes/volumes_mock.go
  cloud/services/networking/loadbalancers_test.go
  cloud/services/networking/mock_networking/doc.go
  cloud/services/networking/mock_networking/loadbalancers_mock.go
  go.mod
  go.sum
Labels: approved, lgtm, size/XXL, release-note-none, cncf-cla: yes
